/**
 * Policy engine tests.
 *
 * The decision tables below are generated by enumerating every combination
 * rather than by listing the interesting ones by hand. A hand-picked table
 * proves what its author already believed; an enumerated one fails when a
 * combinator changes in a way nobody anticipated, which is the only time a
 * decision table earns its keep.
 */

import { describe, it, expect } from '@jest/globals';
import { allOf, anyOf, not } from '../combinators.js';
import { authenticated, confirmationForEffects, permissionPolicy, readOnly } from '../builtins.js';
import type { Policy, PolicyContext, PolicyDecision } from '../types.js';
import type { EffectClassification, OperationDefinition, Principal } from '../../types.js';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function operation(
  overrides?: Partial<OperationDefinition> & {
    readonly effectOverrides?: Partial<OperationDefinition['effects']>;
  },
): OperationDefinition {
  return {
    id: 'transferFunds',
    name: 'transferFunds',
    description: 'Move money between accounts',
    input: { type: 'object' },
    output: { type: 'object' },
    effects: {
      readOnly: false,
      idempotent: false,
      retryable: false,
      idempotencyKeyRequired: true,
      classifications: [],
      ...overrides?.effectOverrides,
    },
    executor: { type: 'test' },
    ...overrides,
  };
}

function context(overrides?: Partial<PolicyContext>): PolicyContext {
  return {
    operation: operation(),
    registryHash: 'abc123def4567890',
    phase: 'invocation',
    ...overrides,
  };
}

type Effect = PolicyDecision['effect'];

/** A policy that always returns the given effect. */
function stub(effect: Effect, id = `stub:${effect}`): Policy {
  return {
    id,
    evaluate(): Promise<PolicyDecision> {
      switch (effect) {
        case 'allow':
          return Promise.resolve({ effect: 'allow', evidence: [] });
        case 'deny':
          return Promise.resolve({
            effect: 'deny',
            code: 'STUB_DENY',
            safeReason: 'stub denied',
            evidence: [],
          });
        case 'confirmation_required':
          return Promise.resolve({
            effect: 'confirmation_required',
            challenge: { id: 'stub-challenge', kind: 'acknowledge', prompt: 'confirm?' },
            evidence: [],
          });
      }
    },
  };
}

const EFFECTS: readonly Effect[] = ['allow', 'deny', 'confirmation_required'];

/**
 * Outcome equality for the algebraic properties.
 *
 * Evidence is deliberately excluded: `allOf([P, P])` evaluates P twice and adds
 * its own note, so evidence can never be equal even when the decision is. The
 * decision — effect, and the payload that rides with it — is what composition
 * is required to preserve.
 */
function outcome(decision: PolicyDecision): string {
  switch (decision.effect) {
    case 'allow':
      return 'allow';
    case 'deny':
      return `deny:${decision.code}:${decision.safeReason}`;
    case 'confirmation_required':
      return `confirmation_required:${decision.challenge.id}`;
  }
}

// ---------------------------------------------------------------------------
// Decision tables — every combination, not a selection
// ---------------------------------------------------------------------------

describe('allOf decision table', () => {
  // deny wins over everything; confirmation_required wins over allow.
  const expected: Record<string, Effect> = {
    'allow,allow': 'allow',
    'allow,deny': 'deny',
    'allow,confirmation_required': 'confirmation_required',
    'deny,allow': 'deny',
    'deny,deny': 'deny',
    'deny,confirmation_required': 'deny',
    'confirmation_required,allow': 'confirmation_required',
    'confirmation_required,deny': 'deny',
    'confirmation_required,confirmation_required': 'confirmation_required',
  };

  for (const left of EFFECTS) {
    for (const right of EFFECTS) {
      const key = `${left},${right}`;
      it(`allOf([${left}, ${right}]) === ${expected[key]}`, async () => {
        const decision = await allOf([stub(left), stub(right)]).evaluate(context());
        expect(decision.effect).toBe(expected[key]);
      });
    }
  }

  it('covers all nine combinations', () => {
    expect(Object.keys(expected)).toHaveLength(EFFECTS.length * EFFECTS.length);
  });
});

describe('anyOf decision table', () => {
  // allow if any allow; deny only if ALL deny; otherwise confirmation_required.
  const expected: Record<string, Effect> = {
    'allow,allow': 'allow',
    'allow,deny': 'allow',
    'allow,confirmation_required': 'allow',
    'deny,allow': 'allow',
    'deny,deny': 'deny',
    'deny,confirmation_required': 'confirmation_required',
    'confirmation_required,allow': 'allow',
    'confirmation_required,deny': 'confirmation_required',
    'confirmation_required,confirmation_required': 'confirmation_required',
  };

  for (const left of EFFECTS) {
    for (const right of EFFECTS) {
      const key = `${left},${right}`;
      it(`anyOf([${left}, ${right}]) === ${expected[key]}`, async () => {
        const decision = await anyOf([stub(left), stub(right)]).evaluate(context());
        expect(decision.effect).toBe(expected[key]);
      });
    }
  }

  describe('reporting an all-denied outcome', () => {
    const denyWith = (id: string, code: string, safeReason: string): Policy => ({
      id,
      evaluate: () => Promise.resolve({ effect: 'deny', code, safeReason, evidence: [] }),
    });

    it('propagates the shared reason when every branch denied identically', async () => {
      const decision = await anyOf([
        denyWith('a', 'FORBIDDEN', 'Only read-only operations are permitted here.'),
        denyWith('b', 'FORBIDDEN', 'Only read-only operations are permitted here.'),
      ]).evaluate(context());

      // "Only read-only operations are permitted here" is worth keeping;
      // "every alternative denied" is not.
      expect(decision.effect === 'deny' && decision.safeReason).toBe(
        'Only read-only operations are permitted here.',
      );
    });

    it('aggregates when branches share a code but deny for DIFFERENT reasons', async () => {
      // Keying uniformity on code alone would report the first reason and
      // silently drop the second, while claiming every policy denied — which
      // a reader takes to mean they denied the same way.
      const decision = await anyOf([
        denyWith('a', 'FORBIDDEN', 'Only read-only operations are permitted here.'),
        denyWith('b', 'FORBIDDEN', 'The caller lacks the permissions this operation requires.'),
      ]).evaluate(context());

      expect(decision.effect === 'deny' && decision.code).toBe('anyOf_all_denied');
    });
  });

  it('a single deny does NOT veto a disjunction', async () => {
    // If it did, anyOf would be indistinguishable from allOf and there would be
    // no way to express an alternative at all.
    const decision = await anyOf([stub('deny'), stub('allow')]).evaluate(context());
    expect(decision.effect).toBe('allow');
  });
});

describe('not decision table', () => {
  const expected: Record<Effect, Effect> = {
    allow: 'deny',
    deny: 'allow',
    confirmation_required: 'deny',
  };

  for (const effect of EFFECTS) {
    it(`not(${effect}) === ${expected[effect]}`, async () => {
      const decision = await not(stub(effect)).evaluate(context());
      expect(decision.effect).toBe(expected[effect]);
    });
  }
});

// ---------------------------------------------------------------------------
// Algebraic properties
// ---------------------------------------------------------------------------

describe('idempotence', () => {
  for (const effect of EFFECTS) {
    it(`allOf([P, P]) is equivalent to P for ${effect}`, async () => {
      const p = stub(effect);
      const single = await p.evaluate(context());
      const doubled = await allOf([p, p]).evaluate(context());
      expect(outcome(doubled)).toBe(outcome(single));
    });

    it(`anyOf([P, P]) is equivalent to P for ${effect}`, async () => {
      const p = stub(effect);
      const single = await p.evaluate(context());
      const doubled = await anyOf([p, p]).evaluate(context());
      expect(outcome(doubled)).toBe(outcome(single));
    });
  }
});

describe('double negation', () => {
  // Holds on the two-valued part of the lattice...
  for (const effect of ['allow', 'deny'] as const) {
    it(`not(not(P)) is equivalent to P for ${effect}`, async () => {
      const p = stub(effect);
      const once = await p.evaluate(context());
      const twice = await not(not(p)).evaluate(context());
      expect(twice.effect).toBe(once.effect);
    });
  }

  // ...and NOT on the third value. This is the one place the algebra breaks,
  // and it breaks in the unsafe direction, so it is pinned rather than left to
  // a comment. If someone "fixes" not() to make double negation total, this
  // fails and they have to decide deliberately.
  it('is NOT an involution on confirmation_required — it escalates to allow', async () => {
    const p = stub('confirmation_required');
    const twice = await not(not(p)).evaluate(context());

    expect(twice.effect).toBe('allow');
    expect(twice.effect).not.toBe('confirmation_required');
  });
});

describe('denial precedence', () => {
  it('one deny beats a hundred allows, wherever it sits', async () => {
    for (const position of [0, 50, 100]) {
      const policies: Policy[] = Array.from({ length: 100 }, (_, i) => stub('allow', `allow-${i}`));
      policies.splice(position, 0, stub('deny', 'the-one-deny'));

      const decision = await allOf(policies).evaluate(context());
      expect(decision.effect).toBe('deny');
    }
  });

  it('one deny beats ninety-nine confirmation_requireds', async () => {
    const policies: Policy[] = Array.from({ length: 99 }, (_, i) =>
      stub('confirmation_required', `confirm-${i}`),
    );
    policies.push(stub('deny'));

    const decision = await allOf(policies).evaluate(context());
    expect(decision.effect).toBe('deny');
  });

  it('reports the first deny in declaration order, not an arbitrary one', async () => {
    const first: Policy = {
      id: 'first',
      evaluate: () =>
        Promise.resolve({ effect: 'deny', code: 'FIRST', safeReason: 'first', evidence: [] }),
    };
    const second: Policy = {
      id: 'second',
      evaluate: () =>
        Promise.resolve({ effect: 'deny', code: 'SECOND', safeReason: 'second', evidence: [] }),
    };

    const decision = await allOf([first, second]).evaluate(context());
    expect(decision.effect === 'deny' && decision.code).toBe('FIRST');
  });
});

// ---------------------------------------------------------------------------
// Empty composition
// ---------------------------------------------------------------------------

describe('empty composition', () => {
  it('allOf([]) allows — the identity element of conjunction', async () => {
    const decision = await allOf([]).evaluate(context());
    expect(decision.effect).toBe('allow');
  });

  it('anyOf([]) denies — nothing is offered that could allow', async () => {
    const decision = await anyOf([]).evaluate(context());
    expect(decision.effect).toBe('deny');
  });
});

// ---------------------------------------------------------------------------
// Failing closed
// ---------------------------------------------------------------------------

describe('failing closed', () => {
  const thrower: Policy = {
    id: 'thrower',
    evaluate: () => {
      throw new Error('boom');
    },
  };

  const rejecter: Policy = {
    id: 'rejecter',
    evaluate: () => Promise.reject(new Error('boom')),
  };

  // A policy from older code, or with a typo, or returning undefined.
  const nonsense = { id: 'nonsense', evaluate: () => Promise.resolve(undefined) } as unknown as Policy;

  it('a policy that throws synchronously becomes a deny, not an allow', async () => {
    const decision = await allOf([thrower]).evaluate(context());
    expect(decision.effect).toBe('deny');
  });

  it('a policy that rejects becomes a deny', async () => {
    const decision = await allOf([rejecter]).evaluate(context());
    expect(decision.effect).toBe('deny');
  });

  it('a policy returning an unrecognised shape becomes a deny', async () => {
    const decision = await allOf([nonsense]).evaluate(context());
    expect(decision.effect).toBe('deny');
  });

  it('a throwing branch does not take down a surrounding anyOf', async () => {
    const decision = await anyOf([thrower, stub('allow')]).evaluate(context());
    expect(decision.effect).toBe('allow');
  });

  it('not(throwing policy) denies rather than inverting the failure into allow', async () => {
    // The inner failure is a deny, and not(deny) is allow — which would turn a
    // crashing policy into an open door. The failure must not round-trip.
    const decision = await not(thrower).evaluate(context());
    expect(decision.effect).toBe('deny');
  });

  // A decision missing its evidence array passed the shape check, and then
  // threw "evidence is not iterable" when a combinator spread it. NESTED, the
  // parent's own evaluateSafely caught that and denied — so a test that only
  // exercised composed trees would have seen nothing wrong. At the ROOT there
  // is no parent to catch it, and the TypeError escaped to the caller: a
  // module whose whole job is containing untrusted policy code, failing open
  // by exactly one layer.
  //
  // Every case below therefore evaluates the combinator AT THE ROOT. That
  // position IS the defect; nested, all of these passed before the fix.
  // Found in QA on PR #117.
  describe('a malformed decision is rejected rather than spread', () => {
    const malformed: readonly (readonly [string, unknown])[] = [
      ['no evidence at all', { effect: 'allow' }],
      ['evidence is not an array', { effect: 'allow', evidence: 'nope' }],
      ['evidence is null', { effect: 'allow', evidence: null }],
      ['evidence contains null', { effect: 'allow', evidence: [null] }],
      ['an evidence entry is a bare string', { effect: 'allow', evidence: ['claim'] }],
      ['an evidence entry lacks a claim', { effect: 'allow', evidence: [{ policyId: 'p' }] }],
      ['deny without a code', { effect: 'deny', safeReason: 'r', evidence: [] }],
      ['confirmation without a challenge', { effect: 'confirmation_required', evidence: [] }],
    ];

    for (const [label, value] of malformed) {
      const policy = {
        id: 'malformed',
        evaluate: () => Promise.resolve(value),
      } as unknown as Policy;

      it(`allOf denies at the root — ${label}`, async () => {
        await expect(allOf([policy]).evaluate(context())).resolves.toMatchObject({
          effect: 'deny',
        });
      });

      it(`anyOf denies at the root — ${label}`, async () => {
        await expect(anyOf([policy]).evaluate(context())).resolves.toMatchObject({
          effect: 'deny',
        });
      });

      it(`negation denies at the root — ${label}`, async () => {
        // Deny, not allow: the substituted denial is this module's own safety
        // response to a failure, and is never inverted into an allowance.
        await expect(not(policy).evaluate(context())).resolves.toMatchObject({
          effect: 'deny',
        });
      });
    }
  });
});

// ---------------------------------------------------------------------------
// Evidence safety
// ---------------------------------------------------------------------------

describe('evidence safety', () => {
  const PRINCIPAL_ID = 'PRINCIPAL-SENTINEL-1a2b3c-do-not-leak';
  const PAYLOAD = 'PAYLOAD-SENTINEL-9z8y7x-do-not-leak';

  const principal: Principal = {
    id: PRINCIPAL_ID,
    type: 'user',
    permissions: ['payments:read'],
    attributes: { sessionToken: 'TOKEN-SENTINEL-do-not-leak' },
  };

  const ctx = context({
    principal,
    input: { accountNumber: PAYLOAD, memo: PAYLOAD },
    operation: operation({
      effectOverrides: { classifications: ['financial'] as readonly EffectClassification[] },
    }),
  });

  const everyBuiltin: readonly Policy[] = [
    authenticated(),
    permissionPolicy({ transferFunds: ['payments:write', 'payments:approve'] }),
    confirmationForEffects(['financial', 'destructive']),
    readOnly(),
  ];

  it('no built-in leaks the principal id, a token, or the request payload', async () => {
    for (const policy of everyBuiltin) {
      const serialised = JSON.stringify(await policy.evaluate(ctx));
      expect(serialised).not.toContain(PRINCIPAL_ID);
      expect(serialised).not.toContain(PAYLOAD);
      expect(serialised).not.toContain('TOKEN-SENTINEL');
    }
  });

  it('a composed tree leaks none of them either', async () => {
    const serialised = JSON.stringify(await allOf(everyBuiltin).evaluate(ctx));
    expect(serialised).not.toContain(PRINCIPAL_ID);
    expect(serialised).not.toContain(PAYLOAD);
    expect(serialised).not.toContain('TOKEN-SENTINEL');
  });

  it('an error message is not copied into the decision', async () => {
    // catch (e) { safeReason: e.message } is the natural way to write this and
    // would drag the payload straight into a field named "safe".
    const leaky: Policy = {
      id: 'leaky',
      evaluate: () => {
        throw new Error(`failed while processing ${PAYLOAD}`);
      },
    };

    const serialised = JSON.stringify(await allOf([leaky]).evaluate(context()));
    expect(serialised).not.toContain(PAYLOAD);
  });

  it('permission NAMES are intentionally present — they describe the request, not the caller', async () => {
    // Stated as an assertion so the omission above reads as a decision rather
    // than an oversight.
    const decision = await permissionPolicy({ transferFunds: ['payments:write'] }).evaluate(ctx);
    expect(JSON.stringify(decision)).toContain('payments:write');
  });
});

// ---------------------------------------------------------------------------
// Built-in behaviour
// ---------------------------------------------------------------------------

describe('authenticated', () => {
  it('denies when no principal is present', async () => {
    const decision = await authenticated().evaluate(context());
    expect(decision.effect).toBe('deny');
    expect(decision.effect === 'deny' && decision.code).toBe('UNAUTHENTICATED');
  });

  it('allows when a principal is present', async () => {
    const decision = await authenticated().evaluate(
      context({ principal: { id: 'u1', type: 'user' } }),
    );
    expect(decision.effect).toBe('allow');
  });
});

describe('permissionPolicy', () => {
  const principal: Principal = { id: 'u1', type: 'user', permissions: ['a', 'b'] };

  it('allows when every required permission is held', async () => {
    const decision = await permissionPolicy({ transferFunds: ['a', 'b'] }).evaluate(
      context({ principal }),
    );
    expect(decision.effect).toBe('allow');
  });

  it('denies when only some required permissions are held', async () => {
    // The conjunctive reading: holding one of two is not enough.
    const decision = await permissionPolicy({ transferFunds: ['a', 'c'] }).evaluate(
      context({ principal }),
    );
    expect(decision.effect).toBe('deny');
  });

  it('denies an unlisted operation by default', async () => {
    const decision = await permissionPolicy({ somethingElse: ['a'] }).evaluate(
      context({ principal }),
    );
    expect(decision.effect).toBe('deny');
  });

  it('allows an unlisted operation only when explicitly configured to', async () => {
    const decision = await permissionPolicy({ somethingElse: ['a'] }, { unlisted: 'allow' }).evaluate(
      context({ principal }),
    );
    expect(decision.effect).toBe('allow');
  });

  it('treats a principal with no permissions as holding none', async () => {
    const decision = await permissionPolicy({ transferFunds: ['a'] }).evaluate(
      context({ principal: { id: 'u1', type: 'user' } }),
    );
    expect(decision.effect).toBe('deny');
  });

  it('does not mistake an inherited Object property for a permission grant', async () => {
    // `required['toString']` is truthy on a plain object literal via the
    // prototype chain. Reaching it would grant an operation nobody listed.
    const decision = await permissionPolicy({}).evaluate(
      context({ principal, operation: operation({ id: 'toString' }) }),
    );
    expect(decision.effect).toBe('deny');
  });
});

describe('confirmationForEffects', () => {
  it('requires confirmation when a classification matches', async () => {
    const decision = await confirmationForEffects(['financial']).evaluate(
      context({
        operation: operation({
          effectOverrides: { classifications: ['financial'] as readonly EffectClassification[] },
        }),
      }),
    );
    expect(decision.effect).toBe('confirmation_required');
  });

  it('allows when no classification matches', async () => {
    const decision = await confirmationForEffects(['financial']).evaluate(
      context({
        operation: operation({
          effectOverrides: { classifications: ['notification'] as readonly EffectClassification[] },
        }),
      }),
    );
    expect(decision.effect).toBe('allow');
  });

  it('produces a stable challenge id for the same operation', async () => {
    const policy = confirmationForEffects(['financial', 'destructive']);
    const ctx = context({
      operation: operation({
        effectOverrides: {
          classifications: ['destructive', 'financial'] as readonly EffectClassification[],
        },
      }),
    });

    const first = await policy.evaluate(ctx);
    const second = await policy.evaluate(ctx);

    expect(first.effect).toBe('confirmation_required');
    expect(first.effect === 'confirmation_required' && first.challenge.id).toBe(
      second.effect === 'confirmation_required' ? second.challenge.id : 'different',
    );
  });
});

describe('readOnly', () => {
  it('allows a read-only operation', async () => {
    const decision = await readOnly().evaluate(
      context({ operation: operation({ effectOverrides: { readOnly: true } }) }),
    );
    expect(decision.effect).toBe('allow');
  });

  it('denies a mutating operation', async () => {
    const decision = await readOnly().evaluate(context());
    expect(decision.effect).toBe('deny');
  });
});

// ---------------------------------------------------------------------------
// The acceptance example, end to end
// ---------------------------------------------------------------------------

describe('the composed example from the issue', () => {
  const policy = allOf([
    authenticated(),
    permissionPolicy({ transferFunds: ['payments:write'] }),
    confirmationForEffects(['financial', 'destructive']),
  ]);

  const financial = operation({
    effectOverrides: { classifications: ['financial'] as readonly EffectClassification[] },
  });

  it('denies an anonymous caller', async () => {
    const decision = await policy.evaluate(context({ operation: financial }));
    expect(decision.effect).toBe('deny');
  });

  it('denies an authenticated caller without the permission', async () => {
    const decision = await policy.evaluate(
      context({ operation: financial, principal: { id: 'u1', type: 'user', permissions: [] } }),
    );
    expect(decision.effect).toBe('deny');
  });

  it('requires confirmation for a permitted caller on a financial operation', async () => {
    const decision = await policy.evaluate(
      context({
        operation: financial,
        principal: { id: 'u1', type: 'user', permissions: ['payments:write'] },
      }),
    );
    expect(decision.effect).toBe('confirmation_required');
  });

  it('allows a permitted caller on an unclassified operation', async () => {
    const decision = await policy.evaluate(
      context({
        operation: operation({ effectOverrides: { classifications: [] } }),
        principal: { id: 'u1', type: 'user', permissions: ['payments:write'] },
      }),
    );
    expect(decision.effect).toBe('allow');
  });

  it('gathers evidence from every branch, not just the deciding one', async () => {
    // Short-circuiting would silently drop the branches after the first
    // failure — exactly the explanation an operator needs when asking why.
    const decision = await policy.evaluate(
      context({
        operation: financial,
        principal: { id: 'u1', type: 'user', permissions: ['payments:write'] },
      }),
    );

    const ids = new Set(decision.evidence.map((e) => e.policyId));
    expect(ids.has('authenticated')).toBe(true);
    expect(ids.has('permissionPolicy')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Phase
// ---------------------------------------------------------------------------

describe('phase', () => {
  it('the same policy tree evaluates in both phases', async () => {
    const policy = allOf([authenticated(), readOnly()]);
    const principal: Principal = { id: 'u1', type: 'user' };
    const readable = operation({ effectOverrides: { readOnly: true } });

    const discovery = await policy.evaluate(
      context({ phase: 'discovery', principal, operation: readable }),
    );
    const invocation = await policy.evaluate(
      context({ phase: 'invocation', principal, operation: readable, input: { a: 1 } }),
    );

    // A policy that ignores `input` must not answer differently at list time
    // and call time — that disagreement is what one shared interface prevents.
    expect(discovery.effect).toBe(invocation.effect);
  });
});
