#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Developer Certificate of Origin (DCO) enforcement.
#
# Verifies that every contributor-authored commit in <base>..<head> carries a
# `Signed-off-by:` trailer whose "Name <email>" matches the commit's author
# or committer identity (case-insensitively). Only GENUINE merges are exempt;
# what makes a merge genuine is defined by is_genuine_merge() below.
#
# Usage:
#   dco-check.sh <base-ref> <head-ref>
#
# Exit codes:
#   0 - every commit in range is signed off (or the range is empty)
#   1 - one or more commits are missing or have a mismatched sign-off
#   2 - usage error / the commit range could not be resolved
#
# GENUINE merge commits are skipped: they are generated by the forge rather
# than authored by the contributor, which is the same rule the upstream DCO app
# applies. That exemption is load-bearing, not theoretical — measured on main
# while writing this, 45 genuine merges exist and only 4 carry a trailer, so
# dropping the exemption outright would fail 41 commits of our own history.
#
# "Genuine" does real work in that sentence (#141). `--no-merges` alone excludes
# anything with 2+ parents, and a commit can acquire a second parent by
# ACCIDENT — a tool that leaves MERGE_HEAD set turns the next ordinary commit
# into one. Such a commit was never examined: not failed, skipped.
#
# On #135's branch every commit carried a second parent, so `--no-merges`
# filtered out the entire branch and the check reported success having verified
# NOTHING. No violation escaped, by luck — the trailers were valid anyway. The
# mechanism that would have caught one simply was not running, which is the
# failure this repository refuses everywhere else: "could not check" must never
# read as "it passed".
#
# Two changes close it, deliberately independent of each other:
#
#   1. A DEGENERATE merge is verified like an ordinary commit. Degenerate means
#      every extra parent is ALREADY an ancestor of the first, so the merge
#      brought in nothing — a merge in shape only. Porcelain git cannot even
#      produce this shape: `git commit` passes its parent list through
#      reduce_heads(), which drops a parent already reachable from another, and
#      `git merge` answers "Already up to date". libgit2 does not reduce, which
#      is why the real instances here came from tooling built on it — and why
#      the test fixture has to use `git commit-tree` to construct one at all.
#      Measured on main: 9 exist, three of them
#      among #135's four, and one (36dfdeb0, "Resolve TypeScript strict mode
#      errors in inspect command") carries NO trailer — a real commit this
#      check skipped in silence and now examines. #135's fourth commit is an
#      honest `git merge` of origin/main and stays exempt, correctly.
#   2. If the range is non-empty but EVERY commit was filtered out, the run
#      fails rather than reporting success. That is the backstop for any future
#      filtering blind spot, not only this one.
#
# Skipped and degenerate merges are COUNTED IN THE OUTPUT too. An exclusion
# nobody can see is how the original defect stayed invisible.

set -euo pipefail

base="${1:-${DCO_BASE_SHA:-}}"
head="${2:-${DCO_HEAD_SHA:-HEAD}}"

if [ -z "$base" ]; then
  echo "usage: dco-check.sh <base-ref> <head-ref>" >&2
  exit 2
fi

# Compare against the merge-base rather than the raw base tip, so commits that
# landed on the base branch after this PR opened are not attributed to it.
if ! merge_base="$(git merge-base "$base" "$head" 2>/dev/null)"; then
  echo "::error::Could not compute a merge-base between '$base' and '$head'." >&2
  echo "::error::The checkout is probably shallow — use actions/checkout with fetch-depth: 0." >&2
  exit 2
fi

all_commits="$(git rev-list "$merge_base..$head")"

if [ -z "$all_commits" ]; then
  echo "No commits in ${merge_base}..${head} — nothing to verify."
  exit 0
fi

# Does this commit bring in history the first parent did not already have?
#
# Checked per extra parent rather than only the second, so an octopus merge is
# classified on the same rule. A commit is a genuine merge if ANY extra parent
# contributes something.
is_genuine_merge() { # is_genuine_merge <sha>
  local sha="$1" parents first rest p rc
  parents="$(git rev-list --parents -n1 "$sha")"
  parents="${parents#* }"                 # drop the commit's own sha
  first="${parents%% *}"
  rest="${parents#* }"

  [ "$rest" != "$parents" ] || return 1   # only one parent — not a merge at all

  for p in $rest; do
    rc=0
    git merge-base --is-ancestor "$p" "$first" >/dev/null 2>&1 || rc=$?
    case "$rc" in
      0) : ;;         # already reachable from the first parent — adds nothing
      1) return 0 ;;  # genuinely brings in history the branch did not have
      # Anything else is git failing to answer — a missing object, a shallow
      # clone. Do NOT read that as "genuine merge, skip it": an unanswerable
      # question is the exact shape of #141. Fail CLOSED and verify the commit;
      # the worst case is asking a contributor to sign a forge-made merge,
      # which is recoverable. Silently certifying an unexamined commit is not.
      *) return 1 ;;
    esac
  done
  return 1                                # every extra parent already reachable
}

commits=""
skipped_merges=0
degenerate_merges=0

while IFS= read -r sha; do
  [ -n "$sha" ] || continue
  if is_genuine_merge "$sha"; then
    skipped_merges=$((skipped_merges + 1))
    continue
  fi
  # Either an ordinary single-parent commit, or a degenerate merge that is one
  # in shape only. Both are the contributor's own work and must be signed.
  if [ "$(git rev-list --parents -n1 "$sha" | wc -w)" -gt 2 ]; then
    degenerate_merges=$((degenerate_merges + 1))
  fi
  commits="${commits}${sha}
"
done <<EOF
$all_commits
EOF

# The range held commits and every one was filtered out. Whatever the reason,
# this run verified nothing — so it must not report success (#141).
if [ -z "$commits" ]; then
  cat >&2 <<EMPTY
::error::Every commit in ${merge_base}..${head} was excluded from DCO verification.

$skipped_merges commit(s) were classified as genuine merges and nothing was left
to check. A run that examines no commits cannot certify anything, so it fails
rather than reporting success.

If these really are all forge-generated merges, the range is wrong — check that
the base ref is the branch this work forked from.
EMPTY
  exit 1
fi

lower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }
trim() { printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

total=0
failed=0
failures=""

while IFS= read -r sha; do
  [ -n "$sha" ] || continue
  total=$((total + 1))

  author="$(git show -s --format='%an <%ae>' "$sha")"
  committer="$(git show -s --format='%cn <%ce>' "$sha")"
  subject="$(git show -s --format='%s' "$sha")"

  # Read sign-offs from the raw message rather than via %(trailers:...) so a
  # commit whose trailer block is interrupted by another line is still
  # accepted. Being permissive here only ever avoids a false failure; a commit
  # with no sign-off at all still fails.
  signoffs="$(git show -s --format='%B' "$sha" | grep -i '^[[:space:]]*Signed-off-by:[[:space:]]*' || true)"

  matched=0
  if [ -n "$signoffs" ]; then
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      value="$(trim "${line#*:}")"
      if [ "$(lower "$value")" = "$(lower "$author")" ] ||
         [ "$(lower "$value")" = "$(lower "$committer")" ]; then
        matched=1
        break
      fi
    done <<EOF
$signoffs
EOF
  fi

  if [ "$matched" -eq 1 ]; then
    printf '  ok    %s %s\n' "${sha:0:12}" "$subject"
  else
    failed=$((failed + 1))
    printf '  FAIL  %s %s\n' "${sha:0:12}" "$subject"
    if [ -z "$signoffs" ]; then
      reason="no Signed-off-by trailer"
    else
      reason="Signed-off-by does not match the author ($author) or committer ($committer)"
    fi
    failures="${failures}  - ${sha:0:12} ${subject}
      ${reason}
"
  fi
done <<EOF
$commits
EOF

echo
echo "Checked $total commit(s); $failed missing a valid sign-off."

# Report what was NOT checked, and what was checked only because of #141. The
# original defect survived because the exclusion was invisible: a run that
# skipped everything looked exactly like a run that passed everything.
if [ "$skipped_merges" -gt 0 ]; then
  echo "Skipped $skipped_merges genuine merge commit(s) (forge-generated; exempt from DCO)."
fi
if [ "$degenerate_merges" -gt 0 ]; then
  echo "Verified $degenerate_merges commit(s) that carry extra parents adding no history,"
  echo "as ordinary commits — see #141."
fi

if [ "$failed" -eq 0 ]; then
  echo "All commits are signed off."
  exit 0
fi

cat >&2 <<REPORT

::error::$failed of $total commit(s) are not signed off (DCO).

Commits needing a sign-off:
$failures
Every commit must carry a Signed-off-by trailer matching its author, to
certify the Developer Certificate of Origin (https://developercertificate.org/).

To fix:

  # sign off the most recent commit
  git commit --amend --signoff

  # or sign off every commit on this branch
  git rebase --signoff origin/main

Then force-push the branch:

  git push --force-with-lease

To sign off automatically from now on, commit with: git commit -s
REPORT

exit 1
