#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Developer Certificate of Origin (DCO) enforcement.
#
# Verifies that every non-merge commit in <base>..<head> carries a
# `Signed-off-by:` trailer whose "Name <email>" matches the commit's author
# or committer identity (case-insensitively).
#
# Usage:
#   dco-check.sh <base-ref> <head-ref>
#
# Exit codes:
#   0 - every commit in range is signed off (or the range is empty)
#   1 - one or more commits are missing or have a mismatched sign-off
#   2 - usage error / the commit range could not be resolved
#
# Merge commits are skipped: they are generated by the forge rather than
# authored by the contributor, which is the same rule the upstream DCO app
# applies.

set -euo pipefail

base="${1:-${DCO_BASE_SHA:-}}"
head="${2:-${DCO_HEAD_SHA:-HEAD}}"

if [ -z "$base" ]; then
  echo "usage: dco-check.sh <base-ref> <head-ref>" >&2
  exit 2
fi

# Compare against the merge-base rather than the raw base tip, so commits that
# landed on the base branch after this PR opened are not attributed to it.
if ! merge_base="$(git merge-base "$base" "$head" 2>/dev/null)"; then
  echo "::error::Could not compute a merge-base between '$base' and '$head'." >&2
  echo "::error::The checkout is probably shallow — use actions/checkout with fetch-depth: 0." >&2
  exit 2
fi

commits="$(git rev-list --no-merges "$merge_base..$head")"

if [ -z "$commits" ]; then
  echo "No non-merge commits in ${merge_base}..${head} — nothing to verify."
  exit 0
fi

lower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }
trim() { printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

total=0
failed=0
failures=""

while IFS= read -r sha; do
  [ -n "$sha" ] || continue
  total=$((total + 1))

  author="$(git show -s --format='%an <%ae>' "$sha")"
  committer="$(git show -s --format='%cn <%ce>' "$sha")"
  subject="$(git show -s --format='%s' "$sha")"

  # Read sign-offs from the raw message rather than via %(trailers:...) so a
  # commit whose trailer block is interrupted by another line is still
  # accepted. Being permissive here only ever avoids a false failure; a commit
  # with no sign-off at all still fails.
  signoffs="$(git show -s --format='%B' "$sha" | grep -i '^[[:space:]]*Signed-off-by:[[:space:]]*' || true)"

  matched=0
  if [ -n "$signoffs" ]; then
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      value="$(trim "${line#*:}")"
      if [ "$(lower "$value")" = "$(lower "$author")" ] ||
         [ "$(lower "$value")" = "$(lower "$committer")" ]; then
        matched=1
        break
      fi
    done <<EOF
$signoffs
EOF
  fi

  if [ "$matched" -eq 1 ]; then
    printf '  ok    %s %s\n' "${sha:0:12}" "$subject"
  else
    failed=$((failed + 1))
    printf '  FAIL  %s %s\n' "${sha:0:12}" "$subject"
    if [ -z "$signoffs" ]; then
      reason="no Signed-off-by trailer"
    else
      reason="Signed-off-by does not match the author ($author) or committer ($committer)"
    fi
    failures="${failures}  - ${sha:0:12} ${subject}
      ${reason}
"
  fi
done <<EOF
$commits
EOF

echo
echo "Checked $total commit(s); $failed missing a valid sign-off."

if [ "$failed" -eq 0 ]; then
  echo "All commits are signed off."
  exit 0
fi

cat >&2 <<REPORT

::error::$failed of $total commit(s) are not signed off (DCO).

Commits needing a sign-off:
$failures
Every commit must carry a Signed-off-by trailer matching its author, to
certify the Developer Certificate of Origin (https://developercertificate.org/).

To fix:

  # sign off the most recent commit
  git commit --amend --signoff

  # or sign off every commit on this branch
  git rebase --signoff origin/main

Then force-push the branch:

  git push --force-with-lease

To sign off automatically from now on, commit with: git commit -s
REPORT

exit 1
