// SPDX-License-Identifier: Apache-2.0
/**
 * Migration guide snippets (#62).
 *
 * §62 asks that each migration ship a Markdown snippet stitched into
 * `docs/migrations/`, and that `--check` show an adopter the snippet applicable
 * to them.
 *
 * Both come from HERE, from the same `Migration` data the engine executes. That
 * is the property worth protecting: a hand-written guide and a codemod drift,
 * and the drift is invisible because nothing compares them. A guide generated
 * from the rules cannot describe a rename the engine does not perform.
 */

import type { Migration, MigrationRule } from './types.js';
import { MIGRATIONS } from './registry.js';

function ruleLine(rule: MigrationRule): string {
  switch (rule.kind) {
    case 'config':
      return rule.to === undefined
        ? `- **Config** — \`${rule.from}\` was removed. ${rule.reason}`
        : `- **Config** — \`${rule.from}\` → \`${rule.to}\`. ${rule.reason}`;
    case 'overlay':
      return rule.to === undefined
        ? `- **Overlay** — \`${rule.from}\` was removed. ${rule.reason}`
        : `- **Overlay** — \`${rule.from}\` → \`${rule.to}\`. ${rule.reason}`;
    case 'source':
      return rule.to === undefined
        ? `- **Source** — \`${rule.from}\` was removed from \`${rule.module}\`. ${rule.reason}`
        : `- **Source** — \`${rule.from}\` → \`${rule.to}\` (from \`${rule.module}\`). ${rule.reason}`;
    case 'output':
      return rule.to === undefined
        ? `- **Output** — \`${rule.surface}\`: \`${rule.from}\` was removed. ${rule.reason}`
        : `- **Output** — \`${rule.surface}\`: \`${rule.from}\` → \`${rule.to}\`. ${rule.reason}`;
  }
}

/** Which rules this migration can apply for you, and which it cannot. */
function automation(migration: Migration): string {
  const automatic = migration.rules.filter((r) => r.kind !== 'output' && r.to !== undefined).length;
  const manual = migration.rules.length - automatic;

  if (automatic === 0) {
    return `Nothing here can be applied automatically — every change needs a decision only you can make.`;
  }
  if (manual === 0) {
    return `\`migrate\` applies all ${String(automatic)} of these for you.`;
  }
  return (
    `\`migrate\` applies ${String(automatic)} of these; the other ${String(manual)} ` +
    `is reported for you to handle, because it touches code or config that is yours rather than ours.`
  );
}

/** The Markdown snippet for one migration. */
export function renderSnippet(migration: Migration): string {
  const lines: string[] = [];

  lines.push(`## ${migration.from} → ${migration.to}`);
  lines.push('');
  lines.push(`**${migration.summary}**`);
  lines.push('');

  if (migration.status === 'prospective') {
    // The banner is the point. An adopter reading a guide for a release that
    // does not exist must be told so in the first thing they read, not in a
    // footnote after they have started editing files.
    lines.push(
      `> ⚠️ **Prospective — this release does not exist yet.** These changes are ` +
        `decided but unshipped, published early so the migration is written by the ` +
        `people making the change rather than reconstructed later. \`migrate\` will ` +
        `not apply it without \`--include-prospective\`.`,
    );
    lines.push('');
  }

  lines.push(`Reference: ${migration.reference}`);
  lines.push('');
  lines.push('### Changes');
  lines.push('');
  for (const rule of migration.rules) lines.push(ruleLine(rule));
  lines.push('');
  lines.push(automation(migration));
  lines.push('');
  lines.push('```bash');
  lines.push(`npx @askturret/mcp migrate --from ${migration.from} --to ${migration.to} --check`);
  lines.push('```');

  return lines.join('\n');
}

/**
 * The whole of `docs/migrations/README.md`.
 *
 * Generated rather than maintained, and a test asserts the committed file
 * matches this output — so an added migration that forgot the doc fails CI
 * instead of shipping an index that silently omits it.
 */
export function renderIndex(migrations: readonly Migration[] = MIGRATIONS): string {
  const lines: string[] = [];

  lines.push('# Migrations');
  lines.push('');
  lines.push('<!-- GENERATED by packages/cli/src/commands/migrate/guide.ts — do not edit by hand. -->');
  lines.push('<!-- Regenerate: node packages/cli/dist/commands/migrate/generate-docs.js -->');
  lines.push('');
  lines.push(
    'Every entry here is generated from the same rules `migrate` executes, so a guide ' +
      'cannot describe a change the tool does not make.',
  );
  lines.push('');
  lines.push('```bash');
  lines.push('npx @askturret/mcp migrate --check              # what would change, changes nothing');
  lines.push('npx @askturret/mcp migrate --from 0.9 --to 1.0  # apply');
  lines.push('```');
  lines.push('');

  const published = migrations.filter((m) => m.status === 'published');
  const prospective = migrations.filter((m) => m.status === 'prospective');

  lines.push('## Published');
  lines.push('');
  if (published.length === 0) {
    // Said plainly. An empty section with no explanation reads as an oversight,
    // and this emptiness is a fact about the project rather than a gap in it.
    lines.push(
      '**None yet.** No release of this project has broken a published surface, so there ' +
        'is nothing to migrate between. The tooling ships first so that the first breaking ' +
        'change arrives with its migration rather than after it.',
    );
    lines.push('');
  } else {
    for (const migration of published) {
      lines.push(renderSnippet(migration));
      lines.push('');
    }
  }

  if (prospective.length > 0) {
    lines.push('## Prospective');
    lines.push('');
    lines.push(
      'Decided but unshipped. Written now so the migration comes from the people making ' +
        'the change; skipped by `migrate` unless you pass `--include-prospective`.',
    );
    lines.push('');
    for (const migration of prospective) {
      lines.push(renderSnippet(migration));
      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}
